// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkK9noPuNKc9R8Se-0Z5m_5rAP1qOfC8',
    appId: '1:1056699658187:web:1208a7b0eb87a52a60d04e',
    messagingSenderId: '1056699658187',
    projectId: 'flutterapp-1d93a',
    authDomain: 'flutterapp-1d93a.firebaseapp.com',
    storageBucket: 'flutterapp-1d93a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBkGcdS5w1jT-nxX70Y1XEFgYl1ymrcg',
    appId: '1:1056699658187:android:d68b8f83bde8822660d04e',
    messagingSenderId: '1056699658187',
    projectId: 'flutterapp-1d93a',
    storageBucket: 'flutterapp-1d93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzHnJ76ttgAlFk16GazRxbO4zpNHcNVU',
    appId: '1:1056699658187:ios:6320c92db6e77f3960d04e',
    messagingSenderId: '1056699658187',
    projectId: 'flutterapp-1d93a',
    storageBucket: 'flutterapp-1d93a.appspot.com',
    iosClientId: '1056699658187-21erhakrln1vg4ol5e0i35e0l7led83t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzHnJ76ttgAlFk16GazRxbO4zpNHcNVU',
    appId: '1:1056699658187:ios:6320c92db6e77f3960d04e',
    messagingSenderId: '1056699658187',
    projectId: 'flutterapp-1d93a',
    storageBucket: 'flutterapp-1d93a.appspot.com',
    iosClientId: '1056699658187-21erhakrln1vg4ol5e0i35e0l7led83t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
